# Regression Analysis

## Imports

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score as R2, mean_absolute_error as MAE, mean_squared_error as  MSE
import matplotlib.pyplot as plt

## Utilities

In [2]:
features = ['OriginAirportID', 'DestAirportID', 'DepTime',
       'DepDelayMinutes', 'DepDel15', 'WindSpeedKmph_Origin',
       'WindDirDegree_Origin', 'WeatherCode_Origin', 'precipMM_Origin',
       'Visibility_Origin', 'Pressure_Origin', 'Cloudcover_Origin',
       'DewPointF_Origin', 'WindGustKmph_Origin', 'tempF_Origin',
       'WindChillF_Origin', 'Humidity_Origin', 'WindSpeedKmph_Dest',
       'WindDirDegree_Dest', 'WeatherCode_Dest', 'precipMM_Dest',
       'Visibility_Dest', 'Pressure_Dest', 'Cloudcover_Dest', 'DewPointF_Dest',
       'WindGustKmph_Dest', 'tempF_Dest', 'WindChillF_Dest', 'Humidity_Dest']
       
target = 'ArrDelayMinutes'

limits = [[0, 100], [100, 200], [200, 500], [500, 1000], [1000, 2000]]

In [3]:
def filterDF(df, lower, upper):
  print([lower, upper])
  return df[(df[target]>=lower) & (df[target]<upper)]

def test(model, X_test, y_test):
  print(X_test.shape)
  predictions = model.predict(X_test)

  print("MAE:", MAE(y_test, predictions))
  print("RMSE:", np.sqrt(MSE(y_test, predictions)))
  print("\n")

## Dataset

In [4]:
df = pd.read_csv("drive/MyDrive/Data/dataset.csv")
df = df[df["ArrDel15"] == 1]
print(df.shape)
df.head()

(388058, 43)

    Year  Quarter  Month  ...  tempF_Dest WindChillF_Dest  Humidity_Dest
1   2016        1      1  ...          42              33             74
11  2016        1      1  ...          35              25             70
13  2016        1      1  ...          35              25             70
17  2016        1      1  ...          35              25             70
19  2016        1      1  ...          35              25             70

[5 rows x 43 columns]

## Splitting X and y

In [5]:
X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [6]:
print(X_test.shape)
X_test.head()

(116418, 29)

         OriginAirportID  DestAirportID  ...  WindChillF_Dest  Humidity_Dest
1616863            10397          11618  ...               76             93
13641              14107          12889  ...               37             63
1619835            12892          13930  ...               85             64
1499982            11292          13930  ...               46             44
667291             12266          12892  ...               69             81

[5 rows x 29 columns]

## Training Regressor

In [7]:
model = RandomForestRegressor()
model.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

## Scores for each Arrival delay interval

In [8]:
testDF = X_test.merge(y_test, left_index=True, right_index=True)
print(testDF.shape)
for limit in limits:
  temp = filterDF(testDF, limit[0], limit[1])
  test(model, temp[features], temp[target])

(116418, 30)
[0, 100]
(97156, 29)
MAE: 10.484335544063645
RMSE: 13.678914833656444


[100, 200]
(14595, 29)
MAE: 17.37699214342811
RMSE: 25.590999411243907


[200, 500]
(4289, 29)
MAE: 19.161091163441363
RMSE: 30.024664005381403


[500, 1000]
(330, 29)
MAE: 16.432727272727274
RMSE: 23.835391053361526


[1000, 2000]
(47, 29)
MAE: 18.45021276595743
RMSE: 24.281772079466293